@startuml
!include <c4/C4_Component.puml>
!include <office/Users/mobile_user.puml>

SHOW_PERSON_SPRITE("mobile_user")

Person(customer, "Customer")
Person(viewer, "Anonymous")

System_Boundary(roadwarrior, "RoadWarrior") {

    Component(acl_customer, "Authorisation & Access Layer", "Controls access to customer owned content")
    Component(acl_viewer, "Anonymous Access Layer", "Allows for access to shared content")

    Container_Boundary(reservation_b, "Reservation") {

        Component(reservation, "Reservation & Trips", "Event Sourced write model managing reservations and trips")
        Component(projection, "Projection", "Projection for reservations with and without trips")
        Component(shared, "Shared content", "Projection of reservations that were marked for sharing")

        Component(notification, "Notification", "Reacts to events from reservation and publishes notification")

        Component(reporter, "Report generator", "Periodically check for candidates for yearly report")
    }

    Container(warehouse, "Analytical Warehouse", "Processes analytical data")
    Container(adapter, "Travel Agency Adapter", "Provides reservation related information")
}

Component_Ext(notification_gateway, "Notification Gateway", "Broadcasts notification via channels: E-Mail, SMS, Push")
Component_Ext(agency, "Travel Agency", "Source of reservation information")


Rel(customer, acl_customer, "Manages reservations and trips")
Rel(acl_customer, reservation, "Manages reservations")
Rel(acl_customer, projection, "Accesses reservations")
Rel(reservation, projection, "Creates & updates projection")

Rel(reservation, notification, "Triggers notification")
Rel(notification, notification_gateway, "Publishes notification")

Rel(reservation, warehouse, "Sends events for analytical purposes")

Rel_L(projection, shared, "Projects for sharing")

Rel(adapter, reservation, "Updates reservation")
Rel(adapter, agency, "Reads for updates")

Rel(viewer, acl_viewer, "Views shared content")
Rel(acl_viewer, shared, "Views shared content")

Rel_U(reporter, projection, "Check for reservations for yearly report and generates report projection")
Rel(reporter, notification, "Triggers notification with yearly report")

@enduml
