@startuml
!include <c4/C4_Component.puml>
!include <office/Users/mobile_user.puml>

SHOW_PERSON_SPRITE("mobile_user")

Person(customer, "Customer")

System_Boundary(roadwarrior, "RoadWarrior") {

    Container_Boundary(acl_customer, "Authorisation & Access Layer", "Controls access to customer owned content") {
        Component(identity, "Identity manager", "Authenticates customers")
        Component(access, "Access manager", "Authorizes customers")
    }

    Component(reservation, "Reservation & Trips", "Event Sourced write model managing reservations and trips")
    Component(projection, "Projection", "Projection for reservations with and without trips")
}

Rel_D(customer, identity, "Authorizes identity")
Rel_D(customer, access, "Accesses with acquired identity")
Rel_L(access, identity, "Verifies identity")
Rel_D(access, reservation, "Manages own reservations")
Rel_D(access, projection, "Accesses own data")

@enduml
